version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: "Build image"
          command: ./build.sh

      - store_artifacts:
          path: pi-gen/deploy
