version: 2
jobs:
  build:
    machine: true
    working_directory: /work
    steps:
      - checkout

      - run:
          name: "Build image"
          command: ./build.sh

      - store_artifacts:
          path: /work/pi-gen/deploy
